### ISSUE TITLE
Trouble getting option.prefix and option.suffix to work

### ISSUE THREAD

**Issue by spacewindow** [alanshaw/grunt-include-replace#48]
Wanted this feature to work with CSS comment before include.

Tried your example option: WORKS

[HTML]
```html
<style>
<!-- @@include('styles.css') -->
</style>
```

[GRUNTFILE]

```javascript
options: {
  prefix: '<!-- @@',
  suffix: ' -->',
}
```

then tried this: DOESN'T WORK

[HTML]

```html
<style>
/* include('styles.css') */
</style>
```

[GRUNTFILE]
```javascript
options: {
  prefix: '/* ',
  suffix: ' */',
}
```

then this, with Regex escapes: DOESN'T WORK

```javascript
options: {
  prefix: '\/\* ',
  suffix: ' \*\/',
}
```

Any tips appreciated, thanks.

**Comment by alanshaw** [comment]
Hi @spacewindow,

There's [a test for this](https://github.com/alanshaw/grunt-include-replace/blob/master/Gruntfile.js#L61-L62) so it should be working.

When you say "DOESN'T WORK", what output are you getting? Perhaps you could post your gruntfile configuration for the includereplace task. I've just run a test to check and the html comment should work with a gruntfile like:

```js
module.exports = function (grunt) {
  grunt.initConfig({
    includereplace: {
      prefixsuffix: {
        options: {
          prefix: '<!-- @@',
          suffix: ' -->'
        },
        src: 'test.html',
        dest: 'dist/',
        expand: true,
        cwd: __dirname
      }
    }
  });
  grunt.loadNpmTasks('grunt-include-replace');
  grunt.registerTask('default', 'includereplace');
};
```

For the css comment style prefix/suffix you'll need to escape the string like so:

```js
module.exports = function (grunt) {
  grunt.initConfig({
    includereplace: {
      prefixsuffix: {
        options: {
          prefix: '\\/\\* ',
          suffix: ' \\*\\/'
        },
        src: 'test.html',
        dest: 'dist/',
        expand: true,
        cwd: __dirname
      }
    }
  });
  grunt.loadNpmTasks('grunt-include-replace');
  grunt.registerTask('default', 'includereplace');
};
```

Since the prefix and suffix are added to the regex string like this:

```js
new RegExp(options.prefix + 'include\\(\\s*["\'](.*?)["\'](,\\s*({[\\s\\S]*?})){0,1}\\s*\\)' + options.suffix);
```

**Comment by spacewindow** [comment]
Thanks so much alan - double escape on those stars and slashes. When I say 'doesn't work' I get no error (because the string is simply bit found) and the 'include' string is not replaced. That's all.

With this fix it totally works. Thanks for the quick response and the very useful tool.

R
