### ISSUE TITLE
Grunt aborting - Warning: undefined is not a function Use --force to continue

### ISSUE THREAD

**Issue by simonwaw** [alanshaw/grunt-include-replace#57]
I have the below config in my grunt file however keep getting an error:

Running "includereplace:dist" (includereplace) task
Warning: undefined is not a function Use --force to continue.

Removing this task from my build works without issue.

Environment:
osx 10.10.3
node v0.12.7
npm 2.14.1

Any ideas??

...
    includereplace: {
        dist: {
            options: {
            },
        files: [
            {
                src: 'src/profile/index.html',
                dest: 'dist/profile/index.html'
            },
            {
                src: 'src/photos/index.html',
                dest: 'dist/photos/index.html'
            },
            {
                src: 'src/admin/index.html',
                dest: 'dist/admin/index.html'
            },
            {
                src: 'src/login/index.html',
                dest: 'dist/login/index.html'
            }
        ]
    }
    },
...

**Comment by alanshaw** [comment]
Could you run with --stack to get the stacktrace printed?

**Comment by arturkot** [comment]
Hello @alanshaw @simonwaw ,

I've just had _very_ similar error just a while ago and it's turned out that it's caused by... Another package. [grunt-zip](https://github.com/twolfson/grunt-zip) to be exact. I've got a feeling that it might be one of the dependencies of grunt-zip (grunt-retro) which is the culprit. So a package inside a package – little inception. ;)

Cheers,

Artur

**Comment by arturkot** [comment]
PS.

The quick fix I've used is downgrading to grunt-include-replace ^2.0.0.
